# Korištenje Pandasa

U nastavku prikazat ćemo neke naprednije mogućnosti Pandasa kroz primjere. Učitajmo podatke za Airbnb.

In [47]:
import pandas as pd

airbnb_data = pd.read_csv('airbnb_new_york_city_listings.csv')

airbnb_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,150,30,48,2019-11-04,0.34,3,341
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Bedford-Stuyvesant,40.684940,-73.957650,Entire home/apt,75,1,408,2021-06-29,5.09,1,212
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,60,30,50,2016-06-05,0.55,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.662650,-73.994540,Entire home/apt,275,5,1,2014-01-02,0.01,1,184
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.764570,-73.983170,Private room,61,2,485,2021-07-18,3.63,1,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,51447515,Gorgeous 2 Bedroom - in Prime Midtown East,51589519,Asi,Manhattan,Midtown,40.755787,-73.965126,Entire home/apt,255,31,0,NaN,NaN,6,364
36720,51449962,"Charming UWS 1-bdrm, 1-office, 1/2 block to Ct...",2971741,Dina Marie,Manhattan,Upper West Side,40.787029,-73.969239,Entire home/apt,306,5,0,NaN,NaN,1,16
36721,51450816,The Hunter IIII,61391963,Stay With Vibe,Manhattan,Upper East Side,40.768950,-73.960455,Entire home/apt,63,30,0,NaN,NaN,96,334
36722,51451029,Rockaway Beach Surf Getaway,10123226,Chase,Queens,Arverne,40.599257,-73.797953,Private room,75,1,0,NaN,NaN,1,87
36723,51451368,Nyc apt in the middle in nyc,17770287,Nina,Manhattan,Murray Hill,40.748655,-73.981209,Entire home/apt,115,30,0,NaN,NaN,11,364

Prikaz u Jupyter Notebook-u koristi `display` funkciju, koju ne moramo posebno pozivati. Ovdje pokazujemo da postoji i da se poziva implicitno.

In [48]:
display(airbnb_data) # Isto kao da je zadnja linija `airbnb_data`

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,150,30,48,2019-11-04,0.34,3,341
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Bedford-Stuyvesant,40.684940,-73.957650,Entire home/apt,75,1,408,2021-06-29,5.09,1,212
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,60,30,50,2016-06-05,0.55,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.662650,-73.994540,Entire home/apt,275,5,1,2014-01-02,0.01,1,184
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.764570,-73.983170,Private room,61,2,485,2021-07-18,3.63,1,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,51447515,Gorgeous 2 Bedroom - in Prime Midtown East,51589519,Asi,Manhattan,Midtown,40.755787,-73.965126,Entire home/apt,255,31,0,NaN,NaN,6,364
36720,51449962,"Charming UWS 1-bdrm, 1-office, 1/2 block to Ct...",2971741,Dina Marie,Manhattan,Upper West Side,40.787029,-73.969239,Entire home/apt,306,5,0,NaN,NaN,1,16
36721,51450816,The Hunter IIII,61391963,Stay With Vibe,Manhattan,Upper East Side,40.768950,-73.960455,Entire home/apt,63,30,0,NaN,NaN,96,334
36722,51451029,Rockaway Beach Surf Getaway,10123226,Chase,Queens,Arverne,40.599257,-73.797953,Private room,75,1,0,NaN,NaN,1,87
36723,51451368,Nyc apt in the middle in nyc,17770287,Nina,Manhattan,Murray Hill,40.748655,-73.981209,Entire home/apt,115,30,0,NaN,NaN,11,364

Za početak analizirajmo kojeg su tipa podataka stupci.

In [49]:
airbnb_data.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

Stupac `last_review` je tipa `object`, a iz podataka i samog naziva stupca vidimo da bi to trebao biti datum. Pokušajmo pretvoriti cijeli taj stupac u `DateTime` tip podatka.

In [50]:
airbnb_data['last_review'] = pd.to_datetime(airbnb_data['last_review'])
airbnb_data.dtypes
# Alternativno: airbnb_data['last_review'] = airbnb_data['last_review'].astype('datetime64')

id                                         int64
name                                      object
host_id                                    int64
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
dtype: object

Kako je `datatime64` tip podatka iz kojeg možemo dobiti samo godinu, to ćemo iskoristiti tako što ćemo stvoriti novi stupac naziva `year`.

In [51]:
airbnb_data['year'] = airbnb_data['last_review'].dt.year
airbnb_data['year']

0        2019.0
1        2021.0
2        2016.0
3        2014.0
4        2021.0
          ...
36719       NaN
36720       NaN
36721       NaN
36722       NaN
36723       NaN
Name: year, Length: 36724, dtype: float64

Provjerimo ako neki podaci nedostaju.

In [52]:
airbnb_data.isnull().sum()

id                                   0
name                                13
host_id                              0
host_name                           23
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                       9415
reviews_per_month                 9415
calculated_host_listings_count       0
availability_365                     0
year                              9415
dtype: int64

Imamo pet kolona koje imaju prazne ćelije. Kolone "name" i "host_name" su tipa object, odnosno tekstualnog tipa, dok su "reviews_per_month" i "last_review_year" decimalni brojevi, a kolona "last_review" je tipa *DateTime*.

Unesimo podatke u prazne ćelije tako da nam kasnije ne utječu na proračune. To će najbolje biti ako za kolonu:
- "name": "No Name Listing"
- "host_name": "J. Doe"
- "reviews_per_month": 0.00
- "last_review_year": 0
- "last_review": '01-01-1970', što bi odgovaralo početku UNIX vremena

Za ovu aktivnost imamo na raspolaganju tri metode:
- *fillna()*
- *replace()*
- *interpolate()*

Mi ćemo koristiti metodu *fillna()*. Kad koristimo `inplace` argumet `True`, ne stvara se kopija, već se podaci promjene na originalnom objektu.

Više detalja o navedenim funkcijama možete pronaći na stranici: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html.

In [53]:
airbnb_data['name'].fillna('No Name Listing', inplace=True)
airbnb_data['host_name'].fillna('J. Doe', inplace=True)
airbnb_data['reviews_per_month'].fillna(0.00, inplace=True)
airbnb_data['year'].fillna(0.00, inplace=True)
airbnb_data['last_review'].fillna('01-01-1970', inplace=True)

Stupac `year` je `float` tip podatka. Godine su cijeli brojevi, pa ćemo napraviti i tu transformaciju.

In [54]:
airbnb_data.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
year                              float64
dtype: object

`last_review` je opet postao `object` tip. Promjenimo i taj stupac zajedno sa `year`.

In [55]:
airbnb_data['year'] = airbnb_data['year'].astype('int64')
airbnb_data['last_review'] = pd.to_datetime(airbnb_data['last_review'])
airbnb_data.dtypes

id                                         int64
name                                      object
host_id                                    int64
host_name                                 object
neighbourhood_group                       object
neighbourhood                             object
latitude                                 float64
longitude                                float64
room_type                                 object
price                                      int64
minimum_nights                             int64
number_of_reviews                          int64
last_review                       datetime64[ns]
reviews_per_month                        float64
calculated_host_listings_count             int64
availability_365                           int64
year                                       int64
dtype: object

Prikazat ćemo trenutno stanje našeg `DateFrame`-a.

In [56]:
airbnb_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,year
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,150,30,48,2019-11-04,0.34,3,341,2019
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Bedford-Stuyvesant,40.684940,-73.957650,Entire home/apt,75,1,408,2021-06-29,5.09,1,212,2021
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,60,30,50,2016-06-05,0.55,1,365,2016
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.662650,-73.994540,Entire home/apt,275,5,1,2014-01-02,0.01,1,184,2014
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.764570,-73.983170,Private room,61,2,485,2021-07-18,3.63,1,255,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,51447515,Gorgeous 2 Bedroom - in Prime Midtown East,51589519,Asi,Manhattan,Midtown,40.755787,-73.965126,Entire home/apt,255,31,0,1970-01-01,0.00,6,364,0
36720,51449962,"Charming UWS 1-bdrm, 1-office, 1/2 block to Ct...",2971741,Dina Marie,Manhattan,Upper West Side,40.787029,-73.969239,Entire home/apt,306,5,0,1970-01-01,0.00,1,16,0
36721,51450816,The Hunter IIII,61391963,Stay With Vibe,Manhattan,Upper East Side,40.768950,-73.960455,Entire home/apt,63,30,0,1970-01-01,0.00,96,334,0
36722,51451029,Rockaway Beach Surf Getaway,10123226,Chase,Queens,Arverne,40.599257,-73.797953,Private room,75,1,0,1970-01-01,0.00,1,87,0
36723,51451368,Nyc apt in the middle in nyc,17770287,Nina,Manhattan,Murray Hill,40.748655,-73.981209,Entire home/apt,115,30,0,1970-01-01,0.00,11,364,0

Odlično, imamo jednu kolonu više od inicijalnog skupa podataka, nemamo praznih ćelija.

Većinu tipova podataka smo očistili, međutim, često se dogodi da nam tekstualni podaci sadrže znakove koje računala ne prikazuju (primjer je znak za novi red '*\n*'). Ti znakovi su tu, no kako nam ne trebaju u podacima, bilo bi ih dobro obrisati. Pandas podržava string metodu *str.strip()* nad *DataFrame* objektom. Ova metoda briše sve posebne znakove, prazna mjesta (razmaknicu ili *space*) te slične znakove na početku i na kraju tekstualnog podatka.

Očistimo i tekstualne podatke pomoću *str.strip()* metode, u svakoj koloni koja ima tekstualni tip podatka.

*INFORMACIJA: možemo koristiti i str.lower() i str.upper() metode ako nam trebaju. U našem slučaju one nisu korisne. Više informacija možete pronaći na stranici: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html.*

In [57]:
airbnb_data['name'] = airbnb_data['name'].str.strip()
airbnb_data['host_name'] = airbnb_data['host_name'].str.strip()
airbnb_data['neighbourhood_group'] = airbnb_data['neighbourhood_group'].str.strip()
airbnb_data['neighbourhood'] = airbnb_data['neighbourhood'].str.strip()
airbnb_data['room_type'] = airbnb_data['room_type'].str.strip()

airbnb_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,year
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,150,30,48,2019-11-04,0.34,3,341,2019
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Bedford-Stuyvesant,40.684940,-73.957650,Entire home/apt,75,1,408,2021-06-29,5.09,1,212,2021
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,60,30,50,2016-06-05,0.55,1,365,2016
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.662650,-73.994540,Entire home/apt,275,5,1,2014-01-02,0.01,1,184,2014
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.764570,-73.983170,Private room,61,2,485,2021-07-18,3.63,1,255,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,51447515,Gorgeous 2 Bedroom - in Prime Midtown East,51589519,Asi,Manhattan,Midtown,40.755787,-73.965126,Entire home/apt,255,31,0,1970-01-01,0.00,6,364,0
36720,51449962,"Charming UWS 1-bdrm, 1-office, 1/2 block to Ct...",2971741,Dina Marie,Manhattan,Upper West Side,40.787029,-73.969239,Entire home/apt,306,5,0,1970-01-01,0.00,1,16,0
36721,51450816,The Hunter IIII,61391963,Stay With Vibe,Manhattan,Upper East Side,40.768950,-73.960455,Entire home/apt,63,30,0,1970-01-01,0.00,96,334,0
36722,51451029,Rockaway Beach Surf Getaway,10123226,Chase,Queens,Arverne,40.599257,-73.797953,Private room,75,1,0,1970-01-01,0.00,1,87,0
36723,51451368,Nyc apt in the middle in nyc,17770287,Nina,Manhattan,Murray Hill,40.748655,-73.981209,Entire home/apt,115,30,0,1970-01-01,0.00,11,364,0

Prikažimo imena svih stupaca.

In [58]:
airbnb_data.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'year'],
      dtype='object')

Vidimo da imamo kolone naziva `price` i `minimum_nights`. Jedna kolona prikazuje cijenu najma po noćenju, a druga prikazuje koliko se minimalno noćenja mora uzeti. Ako spojimo ove dvije kolone, možemo dobiti novu koja će nam prikazati podatak o minimalnom prihodu. Dakle, ako pomnožimo cijenu s minimalnim brojem noćenja, onda je to minimalni prihod koji iznajmljivač može dobiti za svoju nekretninu.

Ako nova kolona prikazuje podatak o minimalnom prihodu, onda ćemo je nazvati `minimal_revenue`.

In [59]:
airbnb_data['minimal_revenue'] = airbnb_data['price'] * airbnb_data['minimum_nights']
airbnb_data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,year,minimal_revenue
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.753560,-73.985590,Entire home/apt,150,30,48,2019-11-04,0.34,3,341,2019,4500
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Bedford-Stuyvesant,40.684940,-73.957650,Entire home/apt,75,1,408,2021-06-29,5.09,1,212,2021,75
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.685350,-73.955120,Private room,60,30,50,2016-06-05,0.55,1,365,2016,1800
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.662650,-73.994540,Entire home/apt,275,5,1,2014-01-02,0.01,1,184,2014,1375
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Midtown,40.764570,-73.983170,Private room,61,2,485,2021-07-18,3.63,1,255,2021,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,51447515,Gorgeous 2 Bedroom - in Prime Midtown East,51589519,Asi,Manhattan,Midtown,40.755787,-73.965126,Entire home/apt,255,31,0,1970-01-01,0.00,6,364,0,7905
36720,51449962,"Charming UWS 1-bdrm, 1-office, 1/2 block to Ct...",2971741,Dina Marie,Manhattan,Upper West Side,40.787029,-73.969239,Entire home/apt,306,5,0,1970-01-01,0.00,1,16,0,1530
36721,51450816,The Hunter IIII,61391963,Stay With Vibe,Manhattan,Upper East Side,40.768950,-73.960455,Entire home/apt,63,30,0,1970-01-01,0.00,96,334,0,1890
36722,51451029,Rockaway Beach Surf Getaway,10123226,Chase,Queens,Arverne,40.599257,-73.797953,Private room,75,1,0,1970-01-01,0.00,1,87,0,75
36723,51451368,Nyc apt in the middle in nyc,17770287,Nina,Manhattan,Murray Hill,40.748655,-73.981209,Entire home/apt,115,30,0,1970-01-01,0.00,11,364,0,3450

Uzmimo samo tri stupca: `room_type`, `price`, `minimal_revenue`. Grupirajmo podatke prema tipu sobe: `room_type`. A nakon toga prema tipu sobe i godini.

In [60]:
airbnb_data[['room_type', 'price', 'minimal_revenue']].groupby('room_type').mean()

                      price  minimal_revenue
room_type
Entire home/apt  213.324779      4949.334480
Hotel room       293.262548      2662.552124
Private room      96.617690      1963.337077
Shared room      107.978297      2575.096828

In [61]:
airbnb_data[['room_type', 'year', 'price']].groupby(['room_type', 'year']).median()

                      price
room_type       year
Entire home/apt 0     180.0
                2010  228.0
                2011  165.0
                2012  150.0
                2013  150.0
                2014  170.0
                2015  150.0
                2016  150.0
                2017  149.0
                2018  150.0
                2019  150.0
                2020  148.0
                2021  150.0
Hotel room      0     370.0
                2016  349.0
                2017  248.0
                2018  125.0
                2019  291.0
                2020  211.5
                2021  165.0
Private room    0      68.0
                2011  349.0
                2012   90.0
                2013  100.0
                2014   80.0
                2015   75.0
                2016   65.0
                2017   65.0
                2018   65.0
                2019   69.0
                2020   63.0
                2021   68.0
Shared room     0      65.0
                2013   50.0
                2014   82.0
                2015   61.5
                2016   95.0
                2017   51.0
                2018   57.0
                2019   55.0
                2020   45.0
                2021   40.0

## Korelacija

Korelacija pokazuje ovisnost izmđu skupova podataka. Strogo gledano, korelacija pokazuje linearnu povezanost. Npr. ako proučavamo dva podatka, ocjenu učenika i vrijme učenja, očekujemo da će ti podaci biti korelirani. Razlog tome je što ako učenik potroši više vremena na učenje može očekivati veću ocjenu. Treba biti oprezan oko korelacije, jer neki podaci su korelirani, ali ne linearno!

Ako je rezultat korelacije 1, to znači da je veza između podataka savršeno linearna. Ako je korelacija jednaka 0, to znači da podaci uopće nisu korelirani (nema linearne veze). Ako je korelacija -1 podaci su savršeno obrnuto linarno povezani. Dobar primjer korelacije -1 bi bila veza između ocjene i vremena provedenog igraćuji video igre.

Izračunajmo korelaciju između stupaca učitanih i očišćenih podataka.

In [62]:
airbnb_data.corr()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,year,minimal_revenue
id,1.000000,0.592363,0.008289,0.095732,0.018652,-0.107520,-0.294396,0.098269,0.220742,0.229577,-0.260503,-0.039593
host_id,0.592363,1.000000,0.034068,0.117111,0.008857,-0.103647,-0.126033,0.129060,0.167007,0.253292,-0.158118,-0.036073
latitude,0.008289,0.034068,1.000000,0.066660,0.020835,0.040860,-0.044333,-0.036331,0.082555,0.025105,-0.044153,0.025437
longitude,0.095732,0.117111,0.066660,1.000000,-0.109681,-0.079185,0.065737,0.058927,-0.059883,0.091318,0.045605,-0.070862
price,0.018652,0.008857,0.020835,-0.109681,1.000000,-0.004452,-0.030849,-0.011955,-0.000460,0.069875,-0.053948,0.623080
minimum_nights,-0.107520,-0.103647,0.040860,-0.079185,-0.004452,1.000000,-0.143130,-0.151884,0.059466,-0.020994,-0.128863,0.376846
number_of_reviews,-0.294396,-0.126033,-0.044333,0.065737,-0.030849,-0.143130,1.000000,0.359701,-0.102862,0.104905,0.273289,-0.053733
reviews_per_month,0.098269,0.129060,-0.036331,0.058927,-0.011955,-0.151884,0.359701,1.000000,-0.043260,0.085797,0.178436,-0.051499
calculated_host_listings_count,0.220742,0.167007,0.082555,-0.059883,-0.000460,0.059466,-0.102862,-0.043260,1.000000,0.242509,-0.228990,0.016462
availability_365,0.229577,0.253292,0.025105,0.091318,0.069875,-0.020994,0.104905,0.085797,0.242509,1.000000,-0.062384,0.034378
year,-0.260503,-0.158118,-0.044153,0.045605,-0.053948,-0.128863,0.273289,0.178436,-0.228990,-0.062384,1.000000,-0.072852
minimal_revenue,-0.039593,-0.036073,0.025437,-0.070862,0.623080,0.376846,-0.053733,-0.051499,0.016462,0.034378,-0.072852,1.000000

Zanima nas korelacija samo za stupac `price` i sve ostale.

In [63]:
airbnb_data.corr()['price']

id                                0.018652
host_id                           0.008857
latitude                          0.020835
longitude                        -0.109681
price                             1.000000
minimum_nights                   -0.004452
number_of_reviews                -0.030849
reviews_per_month                -0.011955
calculated_host_listings_count   -0.000460
availability_365                  0.069875
year                             -0.053948
minimal_revenue                   0.623080
Name: price, dtype: float64

In [64]:
airbnb_data.corr()['price'].sort_values()

longitude                        -0.109681
year                             -0.053948
number_of_reviews                -0.030849
reviews_per_month                -0.011955
minimum_nights                   -0.004452
calculated_host_listings_count   -0.000460
host_id                           0.008857
id                                0.018652
latitude                          0.020835
availability_365                  0.069875
minimal_revenue                   0.623080
price                             1.000000
Name: price, dtype: float64

## Pivot tablice

Pivot tabele ste vjerojatno upoznali u Microsoft Excelu. Njihova primjena je sumirati, sortirati, reorganizirati, grupirati, prebrojati sve ili prosjek podataka u tabeli.

Možda ovo pomogne boljem razumijevanju pivot tabele. Pivot tabela može:
- grupirati pojedinačne zapise, redove u kategorije
- prebrojati elemente u svakoj kategoriji
- sumirati vrijednosti elemenata
- izračunati srednju vrijednost, minimum ili maksimum.

Pandas ima ugrađenu metodu *pivot_table()*. Upoznajmo se s njezinim mogućnostima. Više detalja na: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html?highlight=pivot_table#pandas.pivot_table.

Kad radimo pivotiranje, moramo navesti četiri parametra:

- `values`: podaci koje želimo agregirati
- `index`: redci koje želimo u pivot tablici
- `columns`: stupci koje želimo u pivot tablici
- `aggfunc`: funkcija kojom želimo agregirati - statistika

In [ ]:
pd.pivot_table(airbnb_data, values=['price'], index=['room_type'], columns=['year'], aggfunc='median')

                 price                                                   \
year              0      2010   2011   2012   2013   2014   2015   2016
room_type
Entire home/apt  180.0  228.0  165.0  150.0  150.0  170.0  150.0  150.0
Hotel room       370.0    NaN    NaN    NaN    NaN    NaN    NaN  349.0
Private room      68.0    NaN  349.0   90.0  100.0   80.0   75.0   65.0
Shared room       65.0    NaN    NaN    NaN   50.0   82.0   61.5   95.0


year              2017   2018   2019   2020   2021
room_type
Entire home/apt  149.0  150.0  150.0  148.0  150.0
Hotel room       248.0  125.0  291.0  211.5  165.0
Private room      65.0   65.0   69.0   63.0   68.0
Shared room       51.0   57.0   55.0   45.0   40.0

Za vježbu obradite i analizirajte sljedeće skupove podataka:

- airbnb_new_york_city_reviews_full.csv
- mall_customers.csv - https://www.kaggle.com/kandij/mall-customers
- ocjene.csv

Zanimljive veze koje pronađete vizualizirajte sa znanjem kojeg smo stekli do sad.